feat(LGA-3830): removed trufflehog

diff --git a/.github/workflows/static-analysis.yml b/.github/workflows/static-analysis.yml
--- a/.github/workflows/static-analysis.yml
+++ b/.github/workflows/static-analysis.yml
@@ -7,26 +7,26 @@ jobs:
     name: Run the pip-compile pre-commit hooks
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout the repository
-      uses: actions/checkout@v4
+      - name: Checkout the repository
+        uses: actions/checkout@v4
 
-    - name: Set up Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: '3.13'
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.13"
 
-    - name: Run pip-compile pre-commit
-      id: pip_compile
-      run: |
-        python -m pip install --upgrade pip
-        pip install pre-commit
-        ls requirements/source/* | xargs pre-commit run pip-compile --files
+      - name: Run pip-compile pre-commit
+        id: pip_compile
+        run: |
+          python -m pip install --upgrade pip
+          pip install pre-commit
+          ls requirements/source/* | xargs pre-commit run pip-compile --files
 
-    - name: Check command result
-      if: steps.pip_compile.outcome != 'success'
-      run: |
-        echo "pip-compile failed because the compilation of requirements/source do not match of that in requirements/generated." >&2
-        exit 1
+      - name: Check command result
+        if: steps.pip_compile.outcome != 'success'
+        run: |
+          echo "pip-compile failed because the compilation of requirements/source do not match of that in requirements/generated." >&2
+          exit 1
 
   lint:
     name: Ruff
@@ -49,21 +49,16 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout the repository
-      uses: actions/checkout@v4
+      - name: Checkout the repository
+        uses: actions/checkout@v4
 
-    - name: Set up Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: '3.13'
-        cache: 'pip' # caching pip dependencies
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.13"
+          cache: "pip" # caching pip dependencies
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        python -m pip install -r requirements/generated/requirements-linting.txt
-    - name: Run TruffleHog Scan
-      run: trufflehog3 filesystem .
-    - name: Check for Secrets
-      if: failure()
-      run: exit 1
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install -r requirements/generated/requirements-linting.txt
