Show a custom error message for pip-compile

diff --git a/.github/workflows/static-analysis.yml b/.github/workflows/static-analysis.yml
--- a/.github/workflows/static-analysis.yml
+++ b/.github/workflows/static-analysis.yml
@@ -18,11 +18,17 @@ jobs:
         python-version: '3.12'
 
     - name: Run pip-compile pre-commit
+      id: pip_compile
       run: |
         python -m pip install --upgrade pip
         pip install pre-commit
         ls requirements/source/* | xargs pre-commit run pip-compile --files
-    
+
+    - name: Check command result
+      if: steps.pip_compile.outcome != 'success'
+      run: |
+        echo "pip-compile failed because the compilation of requirements/source do not match of that in requirements/generated." >&2
+        exit 1
 
   lint:
     name: Ruff
