Add pre-commit hook (#14)
Add pre-commit hook

diff --git a/.github/workflows/static-analysis.yml b/.github/workflows/static-analysis.yml
--- a/.github/workflows/static-analysis.yml
+++ b/.github/workflows/static-analysis.yml
@@ -5,6 +5,31 @@ on:
       SONAR_TOKEN:
         required: true
 jobs:
+  pip-compile:
+    name: Run the pip-compile pre-commit hooks
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout the repository
+      uses: actions/checkout@v4
+
+    - name: Set up Python
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.12'
+
+    - name: Run pip-compile pre-commit
+      id: pip_compile
+      run: |
+        python -m pip install --upgrade pip
+        pip install pre-commit
+        ls requirements/source/* | xargs pre-commit run pip-compile --files
+
+    - name: Check command result
+      if: steps.pip_compile.outcome != 'success'
+      run: |
+        echo "pip-compile failed because the compilation of requirements/source do not match of that in requirements/generated." >&2
+        exit 1
+
   lint:
     name: Ruff
     runs-on: ubuntu-latest
